#cd P:/Animal_tracking/codes/fastgeoref

import fastgeoref #import the package

#Run the module to generate data from videos
fastgeoref.run_datagen()

#Run the module to create a region based CNN to automatically detect animals using the data generated above
fastgeoref.run_modelbuild()

#Run the module to generate tracks (detections) of animals using the model built above
fastgeoref.run_auto_tracking()

#Run the module to geo-reference the tracks generated by the auto tracking module
fastgeoref.run_georef()

#Run the module to manually tracks objects and animals
fastgeoref.run_manual_tracking()
